name: Flask Project

on:
  push:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: 

      - name: Add merge comment
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "Merge from dev to main successful. No conflicts detected." | gh issue comment ${{ github.event.issue.number }} --body -
          else
            echo "Merge from dev to main failed. Please resolve any conflicts." | gh issue comment ${{ github.event.issue.number }} --body -
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

